name: Auto Tag and Trigger Build

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: self-hosted
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag --list --sort=-v:refname | head -n 1)
          echo "latest=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          latest="${{ steps.get_tag.outputs.latest }}"
          if [ -z "$latest" ]; then
            new_tag="0.1.0"
          else
            IFS='.' read -r major minor patch <<< "$latest"
            patch=$((patch+1))
            new_tag="$major.$minor.$patch"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "${{ steps.bump.outputs.new_tag }}"
          git push origin "${{ steps.bump.outputs.new_tag }}"

      - name: Trigger image build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run build_release.yml \
            --ref main \
            -f version="${{ steps.bump.outputs.new_tag }}" \
            -f file_name="jammy-cloud-image-amd64"
